POST http://localhost:5000/api/newproduct
content-type: application/json

{
    "title": "Baggie outerwear",
    "description": "Soft baggie outerwear clothes for every weather",
    "price": "10kr"
}
###
