
###
POST http://localhost:5000/api/user/register
content-type: application/json

{
    "username":"test",
    "password":"test123",
    "role": "admin"
}

###

POST http://localhost:5000/api/user/login
content-type: application/json

{
    "username":"Frida",
    "password":"test123",
    "role":"user"
}

###

Get  http://localhost:5000/api/user/logout

###

GET  http://localhost:5000/api/user/authenticated

###

POST http://localhost:5000/api/user/register
content-type: application/json

{
    "username":"testar",
    "password":"test123"
}

###

GET http://localhost:5000/api/user/getUsers

###

DELETE http://localhost:5000/api/user/deleteUser/62a8d531d8347d5ff8f06ef2